### ISSUE TITLE
修复默认的log存放路径BUG

### ISSUE THREAD

**Issue by StarxSky** [CjangCjengh/tacotron2-japanese#16]
# @CjangCjengh  抱歉，由于我在本地为了测试方便而将log存放路径写死，现在希望可以改回！！很抱歉给您带来不便

* 这一行代码：https://github.com/CjangCjengh/tacotron2-japanese/blob/master/train.py#L257 应该改为：https://github.com/StarxSky/tacotron2-japanese/blob/master/train.py#L257
* 这一行代码：https://github.com/CjangCjengh/tacotron2-japanese/blob/master/train.py#L259 应该改为：https://github.com/StarxSky/tacotron2-japanese/blob/master/train.py#L259

**Comment by CjangCjengh** [comment]
收到

**Comment by StarxSky** [comment]
谢谢，给您添麻烦了
